### ISSUE TITLE
Wait until ready obstacle avoider

### ISSUE THREAD

**Issue by asaba96** [Pitt-RAS/iarc7_motion#153]
The check on the timeout should be inside the scope of the while loop, so that we crash as soon as the timeout is reached. As it is currently implemented, we will spin and wait and wait and crash if the dependency is met (assuming after timeout), but this may not happen until way after the timeout has elapsed, which is not desirable.

https://github.com/Pitt-RAS/iarc7_motion/blob/fda734d9503dee070affe90e9c2ea165e1370dd4/src/iarc7_motion/iarc_tasks/task_utilities/obstacle_avoid_helper.py#L54

**Comment by amiller27** [comment]
The check is in the while loop as well, this looks fine to me
